# RabbitMQ
RABBIT_HOSTNAME: "rabbit"
RABBIT_PORT: 5672

# Logging
LOG_NAME: "FLOW_TRACKER"
LOG_DIR: "/opt/DicomFlow/logs"
LOG_LEVEL: 20
LOG_FORMAT: "%(levelname)s ; %(asctime)s ; %(name)s ; %(filename)s ; %(funcName)s ; %(lineno)s ; %(message)s"
LOG_PUB_MODELS:
  - exchange: logs

# FlowTracker
DATABASE_PATH: "/opt/DicomFlow/database/database.sqlite"

# MQSub
SUB_QUEUE_KWARGS:
    queue: ""
    passive: False
    durable: False
    exclusive: False
    auto_delete: True
SUB_PREFETCH_COUNT: 1  # Should not be changed
SUB_MODELS:
  - exchange: "fingerprinter"
    exchange_type: "topic"
    routing_keys: ["success"]
  - exchange: "scheduler"
    exchange_type: "topic"
    routing_keys: ["#"]
  - exchange: "consumer"
    exchange_type: "topic"
    routing_keys: ["#"]
  - exchange: "storescu"
    exchange_type: "topic"
    routing_keys: ["#"]

PUB_ROUTING_KEY_ERROR: "error"

# Dashboard Rules:
DASHBOARD_RULES:
  - on_exchange: "scheduler"
    on_routing_keys: ["error", "fail"]
    status: 400
  - on_exchange: "consumer"
    on_routing_keys: [ "error", "fail" ]
    status: 400
  - on_exchange: "storescu"
    on_routing_keys: ["error", "fail"]
    status: 400

  - on_exchange: "fingerprinter"
    on_routing_keys: ["success"]
    status: 0
  - on_exchange: "fingerprinter"
    on_routing_keys: ["fetch"]
    status: 1
  - on_exchange: "scheduler"
    on_routing_keys: ["fetch"]
    status: 2
  - on_exchange: "scheduler"
    on_routing_keys: [ "success" ]
    status: 3
  - on_exchange: "storescu"
    on_routing_keys: ["fetch"]
    status: 4
  - on_exchange: "storescu"
    on_routing_keys: ["success"]
    status: 5
